import { useState } from 'react'
import { Download, FileSpreadsheet, Check, FileCode, Printer } from 'lucide-react'
import { useAuth } from '../../auth/AuthContext.jsx'

export default function ExportCenter({ reportTitle, filters }) {
  const { user } = useAuth()
  const [downloading, setDownloading] = useState(null)
  const [success, setSuccess] = useState(null)

  const handleExport = (format) => {
    setDownloading(format)
    setSuccess(null)
    setTimeout(() => {
      setDownloading(null)
      setSuccess(format)
    }, 1500)
  }

  return (
    <div style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: '16px', padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 600, fontSize: '1rem', borderBottom: '1px solid var(--color-border)', paddingBottom: '0.75rem' }}>
        <Download size={20} style={{ color: 'var(--color-primary)' }} />
        <span>Self-Service Export Center</span>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '0.75rem' }}>
        <button 
          className="btn btn-outline" 
          onClick={() => handleExport('PDF')}
          disabled={!!downloading}
          style={{ justifyContent: 'center', display: 'flex', alignItems: 'center', gap: '0.35rem', padding: '0.6rem' }}
        >
          <FileCode size={14} /> PDF Report
        </button>
        <button 
          className="btn btn-outline" 
          onClick={() => handleExport('Excel')}
          disabled={!!downloading}
          style={{ justifyContent: 'center', display: 'flex', alignItems: 'center', gap: '0.35rem', padding: '0.6rem' }}
        >
          <FileSpreadsheet size={14} /> Excel Sheet
        </button>
        <button 
          className="btn btn-outline" 
          onClick={() => handleExport('CSV')}
          disabled={!!downloading}
          style={{ justifyContent: 'center', display: 'flex', alignItems: 'center', gap: '0.35rem', padding: '0.6rem' }}
        >
          <FileSpreadsheet size={14} /> CSV Code
        </button>
        <button 
          className="btn btn-outline" 
          onClick={() => handleExport('Print')}
          disabled={!!downloading}
          style={{ justifyContent: 'center', display: 'flex', alignItems: 'center', gap: '0.35rem', padding: '0.6rem' }}
        >
          <Printer size={14} /> Print View
        </button>
      </div>

      {success && (
        <div style={{ padding: '0.75rem 1rem', background: 'var(--color-green-bg)', color: 'var(--color-green-text)', borderRadius: '8px', fontSize: '0.82rem', fontWeight: 500, display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
          <Check size={14} /> Successfully generated and exported {reportTitle} to {success} format!
        </div>
      )}

      {downloading && (
        <div style={{ padding: '0.75rem 1rem', background: 'var(--color-surface-3)', color: 'var(--color-text-muted)', borderRadius: '8px', fontSize: '0.82rem', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
          Compiling export structures...
        </div>
      )}

      {/* Audit & Generation metadata headers block */}
      <div style={{ border: '1px solid var(--color-border)', borderRadius: '12px', padding: '0.88rem 1.25rem', background: 'var(--color-surface-3)', fontSize: '0.78rem', display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
        <div style={{ fontWeight: 600, color: 'var(--color-text-muted)', marginBottom: '0.25rem' }}>COMPILATION METADATA HEADERS</div>
        <div>Institution Group: <strong>ABC Education Group</strong></div>
        <div>Generated By: <strong>{user?.name || 'Authorized Guest'} ({user?.role})</strong></div>
        <div>Timestamp: <strong>{new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}</strong></div>
        <div>Active Filters: <strong>Term 1 · All Campuses · All Departments</strong></div>
      </div>
    </div>
  )
}
